# Generated by Django 2.2.7 on 2019-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
