# Generated by Django 2.2.7 on 2019-11-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
