# Generated by Django 2.2.7 on 2019-12-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_auto_20191203_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('fitem', models.CharField(max_length=10)),
                ('fmat', models.CharField(max_length=500)),
                ('fnut', models.CharField(max_length=100)),
                ('fusage1', models.CharField(max_length=50)),
                ('fusage2', models.CharField(max_length=50)),
                ('fusage3', models.CharField(max_length=50)),
                ('flegalname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('time', models.DateField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pet')),
            ],
        ),
    ]
