# Generated by Django 2.2.7 on 2019-12-06 15:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_favor_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favor_feed',
            name='date',
        ),
        migrations.AddField(
            model_name='favor_feed',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
