# Generated by Django 2.2.7 on 2020-01-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=30)),
                ('incharge', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('postalcode', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('lng', models.CharField(default='', max_length=40)),
                ('lat', models.CharField(default='', max_length=40)),
                ('master_hotel', models.ManyToManyField(related_name='master_hotel', through='hotel.Favor_hotel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favor_hotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
        migrations.AddField(
            model_name='favor_hotel',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
