# Generated by Django 2.2.7 on 2019-12-02 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=8)),
                ('rank', models.CharField(max_length=2)),
                ('full_name', models.CharField(max_length=12)),
                ('incharge', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=11)),
                ('postalcode', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Favor_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
