# Generated by Django 2.2.7 on 2019-12-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=15)),
                ('year_eva', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('postalcode', models.CharField(max_length=5)),
                ('area', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
