# Generated by Django 2.2.7 on 2019-12-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='incharge',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='postalcode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rank',
            field=models.CharField(max_length=20),
        ),
    ]
